# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\rexTwo\Desktop\polling\detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Detail(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(690, 352)
        self.namakandidat = QtWidgets.QLabel(Form)
        self.namakandidat.setGeometry(QtCore.QRect(370, 40, 121, 16))
        self.namakandidat.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.namakandidat.setObjectName("namakandidat")

        self.descKandidat = QtWidgets.QPlainTextEdit(Form)
        self.descKandidat.setGeometry(QtCore.QRect(370, 80, 291, 191))
        self.descKandidat.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.descKandidat.setReadOnly(True)
        self.descKandidat.setObjectName("plainTextEdit")

        self.picture = QtWidgets.QLabel(Form)
        self.picture.setGeometry(QtCore.QRect(30, 30, 281, 291))
        self.picture.setStyleSheet("\n"
"QLabel{\n"
"    image-radius: 8px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.picture.setPixmap(QtGui.QPixmap("./img/acc.png"))
        self.picture.setScaledContents(True)
        self.picture.setObjectName("picture")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Detail()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
