# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\rexTwo\Desktop\polling\home.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import mysql.connector as mc
from view.detail import *
from main import *

class Home(object):
    def koneksi(self):
        con = pymysql.connect(db='polling', user='root', passwd='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)

        self.btnVoting = QtWidgets.QPushButton(Form)
        self.btnVoting.setGeometry(QtCore.QRect(160, 240, 75, 23))
        self.btnVoting.setObjectName("btnVoting")
        self.btnVoting.clicked.connect(self.startVote)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 40, 131, 16))
        self.label.setObjectName("label")

        self.hidden = QtWidgets.QLabel(Form)
        self.hidden.setObjectName("hidden")

        self.hidden2 = QtWidgets.QLabel(Form)
        self.hidden2.setObjectName("hidden2")

        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(70, 80, 248, 127))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(60)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.picture1 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture1.sizePolicy().hasHeightForWidth())
        self.picture1.setSizePolicy(sizePolicy)
        self.picture1.setText("")
        self.picture1.setPixmap(QtGui.QPixmap("./img/acc2.png"))
        self.picture1.setObjectName("picture1")
        self.horizontalLayout.addWidget(self.picture1)

        self.picture2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picture2.sizePolicy().hasHeightForWidth())
        self.picture2.setSizePolicy(sizePolicy)
        self.picture2.setText("")
        self.picture2.setPixmap(QtGui.QPixmap("./img/acc2.png"))
        self.picture2.setObjectName("picture2")
        self.horizontalLayout.addWidget(self.picture2)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(60)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.btnDecs1 = QtWidgets.QPushButton(self.widget)
        self.btnDecs1.setFlat(True)
        self.btnDecs1.setObjectName("btnDecs1")
        self.btnDecs1.clicked.connect(self.detail1)
        self.horizontalLayout_2.addWidget(self.btnDecs1)

        self.btnDecs2 = QtWidgets.QPushButton(self.widget)
        self.btnDecs2.setFlat(True)
        self.btnDecs2.setObjectName("btnDecs2")
        self.horizontalLayout_2.addWidget(self.btnDecs2)

        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(110, 210, 241, 19))
        self.widget1.setObjectName("widget1")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(70)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.select1 = QtWidgets.QRadioButton(self.widget1)
        self.select1.setChecked(False)
        self.select1.setObjectName("select1")
        self.select1.clicked.connect(self.process)

        self.horizontalLayout_3.addWidget(self.select1)

        self.select2 = QtWidgets.QRadioButton(self.widget1)
        self.select2.setChecked(False)
        self.select2.setObjectName("select2")
        self.select2.clicked.connect(self.process)

        self.horizontalLayout_3.addWidget(self.select2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def select_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="polling"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM kandidat")

            self.btnDecs1.setText(mycursor.fetchone()[1])
            self.btnDecs2.setText(mycursor.fetchone()[1])

        except mc.Error as e:
            print("Error occured")

    def detail1(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="polling"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * from kandidat where id=1")

            self.Form = QtWidgets.QDialog()
            self.ui = Detail()
            self.ui.setupUi(self.Form)
            self.ui.namakandidat.setText(self.btnDecs1.text())
            self.ui.descKandidat.setPlainText(mycursor.fetchone()[2])
            self.Form.show()

        except mc.Error as e:
            self.messagebox("Alert", "error")

    def detail2(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="polling"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * from kandidat where id=2")

            self.Form = QtWidgets.QDialog()
            self.ui2 = Detail()
            self.ui2.setupUi(self.Form)
            self.ui2.namakandidat.setText(self.btnDecs2.text())
            self.ui2.descKandidat.setPlainText(mycursor.fetchone()[2])
            self.Form.show()

        except mc.Error as e:
            self.messagebox("Alert", "error")

    def process(self):
        if self.select1.isChecked():
            self.hidden2.setText("1")
        else:
            self.hidden2.setText("2")

    def startVote(self):
        try:
            voter = self.hidden.text()
            kandidat = self.hidden2.text()

            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="polling"
            )

            mycursor = mydb.cursor()
            query = "INSERT INTO record (id_kandidat,id_voter) VALUES(%s, %s)"
            value = (kandidat,voter)
            mycursor.execute(query,value)
            mydb.commit()

            self.messagebox("Alert", "Success")
            self.Form.hide()

        except mc.Error as e:
            print("Error occured")



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Vote"))
        self.btnVoting.setText(_translate("Form", "Vote"))
        self.label.setText(_translate("Form", "Choose your candidate"))
        self.btnDecs1.setText(_translate("Form", "Biodata"))
        self.btnDecs2.setText(_translate("Form", "Biodata"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Home()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
